import os
from dotenv import load_dotenv
from flask import Flask # Required for app context
from app import create_app, db # Assuming your create_app and db are here
from models import User # Assuming User model is in models.py or models/__init__.py
from models.roles import UserRole # Assuming UserRole is in models/roles.py
from utils.email import send_verification_email # Assuming this is your email utility
from sqlalchemy.orm.exc import NoResultFound # For cleaner user existence check

# Load environment variables from .env file
load_dotenv()

def bootstrap_initial_admin():
    """Creates an initial admin user from environment variables if one doesn't exist."""
    initial_admin_email = os.environ.get('INITIAL_ADMIN_EMAIL')
    initial_admin_password = os.environ.get('INITIAL_ADMIN_PASSWORD')

    if not initial_admin_email or not initial_admin_password:
        print("INITIAL_ADMIN_EMAIL or INITIAL_ADMIN_PASSWORD not set in environment variables. Skipping admin creation.")
        return

    # Create a Flask app context to interact with the database and config
    # Use a minimal config for this script, or your existing DevConfig/ProdConfig
    # Ensure the app context is set up correctly to access db and current_app.config
    # If your create_app initializes extensions like mail, ensure it's handled.
    # For this script, we might need a barebones app if full init is too heavy.
    # However, to use send_verification_email, we need app.config for MAIL settings and FRONTEND_URL.
    
    # Attempt to use the existing create_app, assuming it can run in a script context
    # If create_app() requires a specific config or causes issues, a minimal app setup might be needed.
    app = create_app() # Or create_app(ConfigClass) if you have a specific one for scripts

    with app.app_context():
        try:
            # Check if an admin user with this email already exists
            existing_admin = db.session.query(User).filter_by(email=initial_admin_email, role=UserRole.ADMIN.value).one_or_none()
            if existing_admin:
                print(f"Admin user with email {initial_admin_email} already exists.")
                return

            # Check if any user with this email exists, regardless of role
            existing_user = db.session.query(User).filter_by(email=initial_admin_email).one_or_none()
            if existing_user:
                print(f"A user with email {initial_admin_email} already exists but is not an admin. Skipping admin creation.")
                # Optionally, you could update this user to be an admin if that's desired behavior.
                return

            print(f"Creating initial admin user: {initial_admin_email}")
            
            # Create new admin user
            admin_user = User(
                email=initial_admin_email,
                password=initial_admin_password, # The User model constructor handles hashing
                role=UserRole.ADMIN.value
            )
            # User is is_verified=False by default, and verification_token is generated by __init__

            db.session.add(admin_user)
            db.session.commit()

            # Send verification email
            # Ensure MAIL_SERVER, MAIL_PORT etc. and FRONTEND_URL are in your app.config
            # The verification URL needs to be constructed correctly
            try:
                # The verification URL needs to be constructed based on your app's routing
                # Assuming verify_email route is /api/auth/verify-email/<token>
                # And User model's verification_token is already generated
                # The actual verification link sent to the user should point to the frontend
                # which then calls the backend API.
                # Example: http://localhost:5173/verify-email/TOKEN_VALUE
                frontend_url = app.config.get('FRONTEND_URL', 'http://localhost:5173') # Default if not set
                verification_url = f"{frontend_url}/verify-email/{admin_user.verification_token}"
                
                # Check if email sending is enabled in config
                if app.config.get('EMAIL_ENABLED', False):
                    if send_verification_email(admin_user, verification_url):
                        print(f"Verification email sent to {initial_admin_email}. Please verify to activate.")
                    else:
                        print(f"Failed to send verification email to {initial_admin_email}. Please check email configuration.")
                else:
                    print("Email sending is disabled. Admin user created but verification email not sent.")
                    print(f"To manually verify, use token: {admin_user.verification_token} or URL: {verification_url}")

            except Exception as e:
                print(f"Error sending verification email: {e}")
                # Still, the user is created, they might need manual verification or a resend mechanism.

            print(f"Initial admin user {initial_admin_email} created successfully. Role: {admin_user.role}, Verified: {admin_user.is_verified}.")
            print("This admin must verify their email before they can log in.")

        except Exception as e:
            db.session.rollback()
            print(f"Error bootstrapping initial admin: {e}")

if __name__ == "__main__":
    bootstrap_initial_admin()
